# Generated by Django 3.2.5 on 2021-07-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0004_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='walletid',
            field=models.AutoField(default=5000, primary_key=True, serialize=False),
        ),
    ]
