# Generated by Django 3.2.5 on 2021-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0005_alter_wallet_walletid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='walletid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
