version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-kinesis-streams-dynamodb-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wrgfy9vdhrxm"
s3_prefix = "sam-kinesis-streams-dynamodb-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
